image : docker
stages:
  - build

mvn_test_build_push_commit:
  stage: build
  except: 
    - tags
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^(feat|fix|perf|test).*/i
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA . 
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    

mvn_test_build_push_tags:
  stage: build
  only: 
    - tags
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA . 
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA